--- 
apiVersion: v1
kind: Pod
metadata: 
  name: example2
  labels:
    app: hello-world
    env: development
    topic: exiting-containers
spec:
   containers:
    - name: suicidal
      image: hello-world:latest
