apiVersion: v1
kind: Pod

metadata:
  name: example4

  labels:
    purpose: init-container-demo

spec:
  initContainers:
    - name: init-containers-0
      image: alpine
      command:
        - sleep
        - "3s"

    - name: init-containers-1
      image: alpine
      command:
        - sleep
        - "4s"

  containers:
    - name: nginx
      image: nginx:latest

      ports:
        - containerPort: 80